#!/bin/sh
#
# This script prepares a source upload for a PPA build.
#

#
# The identity of the git committer must be known.
#
if [ ! -z "$GIT_AUTHOR_NAME" ] && [ ! -z "$GIT_AUTHOR_EMAIL" ]
then
	SIGNER_NAME="$GIT_AUTHOR_NAME"
	SIGNER_EMAIL="$GIT_AUTHOR_EMAIL"
elif [ ! -z "$GIT_COMMITTER_NAME" ] && [ ! -z "$GIT_COMMITTER_EMAIL" ]
then
	SIGNER_NAME="$GIT_COMMITTER_NAME"
	SIGNER_EMAIL="$GIT_COMMITTER_EMAIL"
else
	echo Error: Unknown committer.
	exit 1
fi

#
# git current and cleanup.
#
git checkout -f
git reset --hard
git pull --force
git ls-files --others | xargs rm -rf

# Don't bother if the repo hasn't changed since the last upload.
#
LAST_UPLOAD=../last-ppa-upload
if [ ! -f ${LAST_UPLOAD} ]
then
	touch ${LAST_UPLOAD}
fi
git log|head -n 1|sed 's/commit //' > ${LAST_UPLOAD}.tmp
if cmp ${LAST_UPLOAD} ${LAST_UPLOAD}.tmp > /dev/null
then
	rm -f ${LAST_UPLOAD}.tmp
	echo No upload needed.
	exit 0
fi
mv ${LAST_UPLOAD}.tmp ${LAST_UPLOAD}

#
# Notify the build scripts that this is a PPA vyuild.
#
cp ${LAST_UPLOAD} `debian/rules print-ppa-file-name`

#
# In order to sign the package you must override the first signer's changelog entry.
#
export DEBEMAIL="$SIGNER_EMAIL"
export DEBFULLNAME="$SIGNER_NAME"
debchange --increment --preserve "PPA Upload"
if ! head -n 1 debian/changelog | grep ubuntu > /dev/null
then
	echo debchange did not work.
	exit 1
fi

#
# Change the version to be that of the git HEAD SHA1.
#
sed -i 's/ubuntu.*)/'`cat ${LAST_UPLOAD}`')/1' debian/changelog

#
# Make sure the third field says hardy.
#
sed -i 's/) .*;/) hardy;/1' debian/changelog

rm -f ../linux_*
dpkg-buildpackage -S -sa -rfakeroot -I.git -I.gitignore -i'\.git.*'

exit 0

