#
# Makefile for the kernel MSS(mmc/sd/sdio) device drivers.
#

# Core
obj-$(CONFIG_MSS)		+= mss_core.o mmc_protocol.o sdio_protocol.o sd_protocol.o

# Media drivers
obj-$(CONFIG_MSS_BLOCK)		+= mss_block.o

# Host drivers
obj-$(CONFIG_MSS_SDHCI)		+= mss_sdhci.o

