#!/bin/bash

stub=debian/control.d/flavour-control.stub
vars=$1

# Defaults
section_image=base
section_headers=devel

. $vars


if [ "$arch" = "" ]; then
	arch=$(basename `dirname $vars`)
fi
flavour=$(basename $vars | sed 's/.*\.//')

cat $stub | grep -v '^#' | sed			\
	-e "s#FLAVOUR#$flavour#g"		\
	-e "s#DESC#$desc#g"			\
	-e "s#ARCH#$arch#g"			\
	-e "s#SUPPORTED#$supported#g"		\
	-e "s#TARGET#$target#g"			\
	-e "s#BOOTLOADER#$bootloader#g" 	\
	-e "s#=PROVIDES=#$provides#g"		\
	-e "s#SECTION_IMAGE#$section_image#g"	\
	-e "s#SECTION_HEADERS#$section_headers#g"
