CC=gcc
#CFLAGS=-Wall
INCLUDES=-I/home/blake/kernel/MPR/include
CFLAGS=-Wall -lpthread ${INCLUDES}


all: recordEvent replayEvent replay_test simple xsimple
recordEvent:
replayEvent:
replay_test:
simple:
xsimple:
#	gcc -Wall -lpthread replay_test.c -o replay_test
crew_test:


clean:
	rm -f *.o recordEvent replayEvent replay_test

