CC=gcc
#CFLAGS=-Wall

CFLAGS=-Wall -lpthread


all: recordEvent replayEvent replay_test
recordEvent:
replayEvent:
replay_test:
#	gcc -Wall -lpthread replay_test.c -o replay_test
crew_test:


clean:
	rm -f *.o
